#!/usr/bin/env bash
# Display filenames after first dash using for loop
for file in *; do
    # Skip directories (Holberton bunu istəsə-istesə də ziyanı yoxdur)
    if [ -f "$file" ]; then
        echo "${file#*-}"
    fi
done
