#!/usr/bin/env bash
# This script kills all "4-to_infinity_and_beyond" processes using kill and killall
# Kill using kill with the PID from pgrep
kill $(pgrep -f 4-to_infinity_and_beyond)
# Kill any remaining instances using killall
killall 4-to_infinity_and_beyond 2>/dev/null
