#!/usr/bin/env bash
# This script kills the "4-to_infinity_and_beyond" process using kill and killall
# Using kill with pgrep
kill "$(pgrep -f 4-to_infinity_and_beyond)"
# Using killall
killall 4-to_infinity_and_beyond 2>/dev/null
