#!/usr/bin/env bash
# This script prints a message indefinitely and reacts to SIGTERM
# Trap SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM
# Infinite loop
while true; do
  echo "To infinity and beyond"
  sleep 2
done
